name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build Framework-Dependent (Ultra Light)
        run: |
          dotnet publish Mobicon/Mobicon.csproj -c Release -o ./publish

      - name: Compress Release Folder
        shell: pwsh
        run: |
          Compress-Archive -Path ./publish/* -DestinationPath ./Mobicon-${{ github.ref_name }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Mobicon-${{ github.ref_name }}.zip
          name: Mobicon ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
